# Unified credentials parameters for AKS and VM flows.
# Populate required values before running setup-credentials.sh.
# Optional ELK_* entries may be left blank to skip.

- name: ORC_SSOUSER
  value: ""
  description: Oracle SSO user (AKS flow)
- name: ORC_SSOPSW
  value: ""
  description: Oracle SSO password (AKS flow)
- name: WDT_RUNTIMEPSW
  value: ""
  description: WDT encryption/password (AKS)
- name: WLS_PSW
  value: ""
  description: WebLogic admin password (fallback to WDT_RUNTIMEPSW if blank)
- name: WLS_USERNAME
  value: "weblogic"
  description: WebLogic admin username (AKS)
- name: DB_PASSWORD
  value: "Secret123!"
  description: Sample database password (AKS)
- name: OTN_USERID
  value: ""
  description: Oracle SSO user (VM flow naming)
- name: OTN_PASSWORD
  value: ""
  description: Oracle SSO password (VM flow naming)
- name: USER_EMAIL
  value: ""
  description: Git user email (VM)
- name: USER_NAME
  value: ""
  description: Git user name (VM)
- name: GIT_TOKEN
  value: ""
  description: GitHub personal access token (VM)
- name: LOCATION
  value: "eastus"
  description: Azure region (common)
- name: ELK_URI
  value: ""
  description: Elastic server URI (optional VM)
- name: ELK_USER_NAME
  value: ""
  description: Elastic user name (optional VM)
- name: ELK_PSW
  value: ""
  description: Elastic password (optional VM)
