name: New Tag
on:
  workflow_dispatch:
    inputs:
      tagname:
        description: 'Specify Tag name to create/update.'
        required: true
        default: '2021-10-13-01-Q4'
      ref:
        description: 'Specify Git Ref if needed.'
        required: false
        default: 'refs/heads/main'
      pushTagUpstream:
        description: 'If non-empty, will push tag to upstream.'
        required: false
env:
  tagbranch: "tagbranch"
  gitToken: ${{ secrets.GIT_TOKEN }}
  refArmttk: d97aa57d259e2fc8562e11501b1cf902265129d9
  refJavaee: c073dee94765142158f62e5a3bee0f255dd7c3a0
  upstreamUserName: "oracle"
  repoName: "weblogic-azure"
  userEmail: ${{ secrets.USER_EMAIL }}
  userName: ${{ secrets.USER_NAME }}

jobs:
  newtag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ env.repoName }}
        uses: actions/checkout@v2
        with:
          path: ${{ env.repoName }}
          ref: ${{ github.event.inputs.ref }}
      - name: Checkout azure-javaee-iaas
        uses: actions/checkout@v2
        with:
          repository: Azure/azure-javaee-iaas
          path: azure-javaee-iaas
          ref: ${{ env.refJavaee }}
      - name: Checkout arm-ttk
        uses: actions/checkout@v2
        with:
          repository: Azure/arm-ttk
          path: arm-ttk
          ref: ${{ env.refArmttk }}
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build azure-javaee-iaas
        run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml

      - name: Build ${{ env.repoName }}
        run: |
          cd ${{ env.repoName }}
          mvn -Ptemplate-validation-tests clean install --file weblogic-azure-vm/arm-oraclelinux-wls/pom.xml
          mvn -Ptemplate-validation-tests clean install --file weblogic-azure-vm/arm-oraclelinux-wls-admin/pom.xml
          mvn -Ptemplate-validation-tests clean install --file weblogic-azure-vm/arm-oraclelinux-wls-cluster/pom.xml
          mvn -Ptemplate-validation-tests clean install --file weblogic-azure-vm/arm-oraclelinux-wls-dynamic-cluster/pom.xml

      - name: Create new tag
        run: |
          cd ${{ env.repoName }}

          git config --global core.longpaths true
          git config --global user.email $userEmail
          git config --global user.name $userName

          authGitPath=https://$gitToken@github.com/$userName/${{ env.repoName }}.git

          echo "Create tag branch"
          remoteBranches=$(git ls-remote --heads)
          echo ${remoteBranches}
          if [[ -n `echo ${remoteBranches} | grep "${tagbranch}"` ]]; then
            git push ${authGitPath} --delete ${tagbranch} -f
          fi

          if [[ -n `git branch --all | grep "${tagbranch}"` ]]; then
            git branch -D ${tagbranch} 
          fi

          git checkout -b ${tagbranch}

          # replace pids
          export targetARM="target"
          for d in weblogic-azure-vm/*/ ; do
              # for admin offer and single node offer
              if [ -d ${d}${targetARM} ];then
                list=$(find ${d}${targetARM} | grep ".json")
                  for file in ${list}; do
                      sourcePath=$(echo "$file" | sed "s:target:src/main:g")
                      if test -f "$sourcePath"; then
                          echo "Replace ${sourcePath} with ${file}"
                          cp -f $file $sourcePath
                      fi
                  done
              fi

              for d1 in $d*/; do
                  if [ ! -d ${d1}${targetARM} ];then  
                      continue;
                  fi

                  list=$(find ${d1}${targetARM} | grep ".json")
                  for file in ${list}; do
                      sourcePath=$(echo "$file" | sed "s:target:src/main:g")
                      if test -f "$sourcePath"; then
                          echo "Replace ${sourcePath} with ${file}"
                          cp -f $file $sourcePath
                      fi
                  done
              done
          done

          git status
          git add --all
          git commit -m "hard code pids"
          git fetch --unshallow
          git push ${authGitPath} ${tagbranch} -f

          # remove existing tag
          tagname=${{ github.event.inputs.tagname }}
          if [[ -n `git ls-remote --tags | grep "${tagname}"` ]]; then 
              git push ${authGitPath} --delete ${tagname} -f
          fi

          # create new tag
          git tag ${tagname}
          git push ${authGitPath} ${tagname} -f
          git push ${authGitPath} --delete ${tagbranch} -f
          if [[ -n ${{ github.event.inputs.pushTagUpstream }} ]]; then
              git remote add upstream https://github.com/${{ env.upstreamUserName }}/${{ env.repoName }}.git
              git push upstream ${tagname}
          fi
